[color]
background = {color0}
;background-alt = {color1}
background-alt = #00000000
foreground = {color7}
foreground-alt = {color7}
primary = {color2}
red = {color1}
green = {color2}
yellow = {color3}

