;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
;background = #211C40
;background-alt = #00000000
;background-alt = ${xrdb:color1:#222}
;foreground = #D8DEE9
;foreground-alt = #33D8DEE9
;primary = #D9B79A
;red = #A66D6D
;green = #592D39
;yellow = #F2D0A7

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;
;
;; colors pywal
background = ${xrdb:color0:#222}
background-alt = #00000000
foreground =  ${xrdb:color7:#fff}
foreground-alt =  ${xrdb:color7:#fff}
primary =  ${xrdb:color2:#fff}
red =  ${xrdb:color1:#f00}
green =  ${xrdb:color2:#0f0}
yellow =  ${xrdb:color3:#ff0}

;
