# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
# EA Desktop - mandar al fondo y no robar foco
windowrulev2 = workspace special silent, class:^(steam_app_1222680)$, title:^(EA Desktop)$
windowrulev2 = noinitialfocus, class:^(.*EA.*)$
windowrulev2 = noinitialfocus, title:^(EA Desktop)$

# cava
# GLava visualizer
windowrulev2 = float, class:^(GLava)$
windowrulev2 = pin, class:^(GLava)$
windowrulev2 = noborder, class:^(GLava)$
windowrulev2 = noshadow, class:^(GLava)$
windowrulev2 = nofocus, class:^(GLava)$
windowrulev2 = noblur, class:^(GLava)$
windowrulev2 = xray 1, class:^(GLava)$
windowrulev2 = move 0 965, class:^(GLava)$
windowrulev2 = noinitialfocus, class:^(GLava)$
windowrulev2 = size 1920 200, class:^(GLava)$
