;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
;background = #211C40
;background-alt = #00000000
;background-alt = ${xrdb:color1:#222}
;foreground = #D8DEE9
;foreground-alt = #33D8DEE9
;primary = #D9B79A
;red = #A66D6D
;green = #592D39
;yellow = #F2D0A7

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;
;
;; colors pywal

background = ${colors.background}
background-alt = ${colors.background}
foreground = ${colors.foreground}
foreground-alt = ${colors.foreground}
primary = ${colors.color2}
red = ${colors.color1}
green = ${colors.color2}
yellow = ${colors.color3}
